### PR TITLE
numpy type aliases replaced by builtin types

### PR DESCRIPTION
**Pull request by simontamayo**
Dear devs,
This PR addresses the issue that I posted here: https://github.com/scikit-learn-contrib/boruta_py/issues/101
Implemented changes include:

- replacing `np.float` by `float`
- replacing `np.bool` by `bool`
- replacing `np.int` by `int`

### CODE REVIEW

**Comment by danielhomola** [comment]
Thanks for this!

**Comment by EmmaTomps** [comment]
This may be a stupid question, but has this change been reflected when downloading the package from pip? I still get the error "AttributeError: module 'numpy' has no attribute 'int'". Says I am using versions 0.3

**Comment by 3zhang** [comment]
> This may be a stupid question, but has this change been reflected when downloading the package from pip? I still get the error `AttributeError: module 'numpy' has no attribute 'int'`. Says I am using versions 0.3

The package on pypi is three years old. So I don't think so.

**Comment by rodrigc** [comment]
This GitHub Action pushes new versions of the package to PyPi:
https://github.com/scikit-learn-contrib/boruta_py/blob/master/.github/workflows/publish-to-pypi.yml

In order to trigger this GHA, a new release tag needs to be pushed to this repository.  See discussion here: https://github.com/scikit-learn-contrib/boruta_py/issues/111

**Pull request merged**
